// Entry point for Astro SSR on Netlify
exports.handler = async function(event, context) {
  // This is just a placeholder - the actual function is generated by Astro
  return {
    statusCode: 200,
    body: JSON.stringify({
      message: "This function is automatically replaced by Astro's Netlify adapter"
    })
  };
};
